[2020-04-21 18:49:29,282] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:50:04,784] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:51:51,157] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:52:27,587] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:54:46,799] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:55:39,608] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:56:19,264] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-21 18:57:13,106] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:52} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/music?type=playlist&limit=1", "request": null, "response": {"name": "1985. Les 50 meilleurs Tubes de l'ann\u00e9e en France. Best of Top Hits Ann\u00e9es 80.", "link": "https://open.spotify.com/playlist/5PplTbbk6EurkETZjKfRpu"}}
[2020-04-22 08:54:11,529] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 08:54:11,537] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
[2020-04-22 08:57:55,562] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 21, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 08:57:55,567] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {}, "response": {"message": "Internal Server Error"}}
[2020-04-22 08:58:03,018] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 21, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 08:58:03,019] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 08:59:06,978] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 21, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 08:59:06,979] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 08:59:34,821] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:54} WARNING - REQUEST_LOG	{"method": "POST", "code": "200 OK", "url": "/client?", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"id": 1, "client_key": "internal", "client_secret": "8b41e2fccc8c5e5bb593a261428b73dd560b0c200dd9ea2b7bc06e0b7e3dc279fa93bbc7d231ac5fa47bb2406eee69857ef766a0f609c9c11c3daa61e0ff3c91", "status": 1, "salt": "aac4b5ceaa5847deb7cdb7e9f452fc64"}}
[2020-04-22 09:00:22,741] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:00:22,743] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:00:53,349] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:00:53,350] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:01:55,647] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:01:55,650] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:02:00,040] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:02:00,041] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:02:09,926] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:02:09,928] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:02:10,566] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:02:10,567] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:02:10,902] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2020-04-22 09:02:10,903] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:02:25,100] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:54} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "url": "/auth?client_key=internal&client_secret=internal", "request": {"client_key": "internal", "client_secret": "internal", "status": 1}, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODc1MjA5NDUsIm5iZiI6MTU4NzUyMDk0NSwianRpIjoiYTI2NTRiNjQtNWFmMi00NWMwLWE2MTctNzc2MjFlYmRhN2QyIiwiZXhwIjoxNTg3NjA3MzQ1LCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaWQiOjEsImNsaWVudF9rZXkiOiJpbnRlcm5hbCIsInN0YXR1cyI6MSwic2FsdCI6ImFhYzRiNWNlYWE1ODQ3ZGViN2NkYjdlOWY0NTJmYzY0In19.r_RCLWVwqaSHcMPx28rR8aqgzSGO3rLw1IOvSTDJWOo"}}
[2020-04-22 09:03:22,509] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "uri": "/face?", "request": null, "response": {"message": {"picture": "Missing required parameter in an uploaded file"}}}
[2020-04-22 09:03:56,767] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 09:03:56,769] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:04:42,952] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 09:04:42,954] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:05:45,159] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 09:05:45,160] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:06:29,357] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 09:06:29,360] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
[2020-04-22 09:06:44,401] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "uri": "/face?", "request": null, "response": {"message": {"picture": "Missing required parameter in an uploaded file"}}}
[2020-04-22 09:07:14,587] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "uri": "/face?", "request": null, "response": {"message": {"picture": "Missing required parameter in an uploaded file"}}}
[2020-04-22 09:08:15,655] {/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /music [GET]
Traceback (most recent call last):
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/vir/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/music/resources.py", line 27, in get
    years = (datetime.date.today().year)-umur
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
[2020-04-22 09:08:15,656] {/home/alta18/Documents/PROJEK/API-AjiyoPI-/Tugas Projek: API (Aji, yoPI)/blueprints/__init__.py:64} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/music?type=playlist&limit=1", "request": null, "response": {"message": "Internal Server Error"}}
